### PR TITLE
Adding cp-all-in-one-flink

### PR DESCRIPTION
**Pull request by jimbethancourt**
### Description 

_What behavior does this PR change, and why?_
Adds a cp-all-in-one version with Flink.  Based on cp-all-in-one-kraft.  Removed all KSQL components.

### Author Validation

_Describe the validation already done, or needs to be done, by the PR submitter._

### Reviewer Tasks

_Describe the tasks/validation that the PR submitter is requesting to be done by the reviewer._

### CODE REVIEW

**Comment by jimbethancourt** [comment]
@davetroiano can you help here?  I'm not sure what I need to do to progress this PR.

**Comment by davetroiano** [comment]
@jimbethancourt thank you for the PR! Keeping in the spirit of this repo having examples that run all of CP in one Docker Compose, ksqlDB should be included in the example. Community members who want to run only Flink and not ksqlDB can always delete the ksqlDB services to opt out, but the default starting point should include it.

> * I've signed the CLA, but the PR wants me to sign it again and I can't seem to do that.

Not sure about this - what happens when you try to visit [this](https://cla-assistant.io/confluentinc/cp-all-in-one?pullRequest=142)? if you can share some more details / errors you're seeing, I'll look into it with an admin.

> * I can't view the Jenkins error on the Jenkins server.

You can ignore the error - it's an expected error due to the build not running

**Comment by jimbethancourt** [comment]
@davetroiano I've updated the docker-compose.yml to include the KSQL docker images.  I've also updated the top level README.md file to include descriptions of the kraft and flink Docker Compose files and the README.md in the flink directory to mention that the Flink Job manager can be found on port 9081.  

It looks like the CLA issue has gone away 🙂

Thanks!

**Comment by jimbethancourt** [comment]
@davetroiano I believe this PR is ready to be merged.  Please let me know if there is any further action you'd like me to take.

Thanks,
Jim

**Review by davetroiano — APPROVED** [review]
LGTM! thanks again for the PR @jimbethancourt

**Pull request merged**
